In [1]:
from TTLinear import TTLinear

In [2]:
import torch
weights = torch.rand(768, 3072)

In [3]:
a = TTLinear(in_features = 3072, out_features = 768, ranks =[72, 72, 72] , input_dims = [8, 8, 6, 8], output_dims= [4, 6, 8 ,4])

In [4]:
dummy_matrix = torch.randn(weights.shape)
a.set_weight_with_fisher(weights, dummy_matrix)

tensor.shape, fisher_tensor.shape ranks torch.Size([32, 48, 48, 32]) torch.Size([32, 48, 48, 32]) [72, 72, 72]
in ful rank tt data.shape torch.Size([32, 48, 48, 32])
resh shape torch.Size([1536, 1536])
resh shape torch.Size([73728, 32])
resh shape torch.Size([1024, 1])
in ful rank tt fisher data.shape torch.Size([32, 48, 48, 32])
resh.shape[d1] < resh.shape[d2]
i shape 0 torch.Size([32, 32])
resh shape in torch.Size([1536, 1536])
else
aa.shape torch.Size([32, 48, 1536])
I shape torch.Size([1536, 1536])
resh shape torch.Size([73728, 32])
else
aa.shape torch.Size([32, 32])
I shape torch.Size([32, 32])
resh shape torch.Size([1024, 1])
torch.Size([1, 32, 32])
tensor([[[ -86.8205,    0.0000,    0.0000,  ...,    0.0000,    0.0000,
             0.0000],
         [   0.0000,  105.2493,    0.0000,  ...,    0.0000,    0.0000,
             0.0000],
         [   0.0000,    0.0000, -228.7407,  ...,    0.0000,    0.0000,
             0.0000],
         ...,
         [   0.0000,    0.0000,    0.0000, 

RuntimeError: mat1 and mat2 shapes cannot be multiplied (32x32 and 1536x1536)

In [ ]:
for core in a.weight.cores:
    print (core.shape)

In [5]:
import tntorch as tn
for core in a.weight.fcores:
    print (core[0][1])
    print (torch.sum(core))
    
    
    IU = tn.right_unfolding(core, batch=False)
    print (IU.shape)
    print (IU.sum(1))
    print ("\n")

tensor([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
tensor(32.)
torch.Size([1, 1024])
tensor([32.])


tensor([[-0.9855, -1.2057, -1.4221,  ..., -1.1640, -0.3082,  0.5422],
        [-0.7356,  0.4779, -0.4528,  ..., -0.5216, -0.8142, -0.0956],
        [-0.7914, -1.1371,  0.2635,  ..., -2.5257,  0.6728, -0.5346],
        [ 2.1108,  0.6850,  0.8147,  ...,  0.3590,  1.1142,  0.1589],
        [-0.0512, -1.1335, -0.0638,  ...,  0.2236,  1.2671, -0.3169],
        [ 0

## Create batch of objects

In [3]:
import torch
d = 768
batch_size = 128
seq_length = 2
n_blocks = 12
ranks = [100, 100, 100]
input_dims = [4, 6, 8, 4]
output_dims = [8, 8, 6, 8]

tt_args = {
        "ranks": ranks,
        "input_dims": input_dims,
        "output_dims": output_dims,
}

model = TTLinear(d, 4 * d, **tt_args)

x = torch.rand(batch_size, seq_length, d, requires_grad=True)
pred = model(x)
loss = pred.norm()
loss.backward()

In [4]:
model

TTLinear(
  (cores): ParameterList(
      (0): Parameter containing: [torch.FloatTensor of size 1x4x8x32]
      (1): Parameter containing: [torch.FloatTensor of size 32x6x8x100]
      (2): Parameter containing: [torch.FloatTensor of size 100x8x6x32]
      (3): Parameter containing: [torch.FloatTensor of size 32x4x8x1]
  )
)

In [4]:
import torch
weights = torch.rand(3072, 768)
dummy_matrix = torch.randn(weights.shape)
model.set_weight_with_fisher(weights, dummy_matrix)

tensor.shape, fisher_tensor.shape ranks torch.Size([32, 48, 48, 32]) torch.Size([32, 48, 48, 32]) [100, 100, 100]
self.cores shape [torch.Size([1, 32, 32]), torch.Size([32, 48, 1536]), torch.Size([1536, 48, 32]), torch.Size([32, 32, 1])]
self.fcores shape [torch.Size([1, 32, 32]), torch.Size([32, 48, 1536]), torch.Size([1536, 48, 32]), torch.Size([32, 32, 1])]
mu 3
I unfold shape torch.Size([32, 32])
mu core shape torch.Size([32, 32, 1])
after mu core shape torch.Size([32, 32, 1])
after mu-1 core shape torch.Size([1536, 48, 32])
mu 2
I unfold shape torch.Size([1536, 1536])
mu core shape torch.Size([1536, 48, 32])
after mu core shape torch.Size([100, 48, 32])
after mu-1 core shape torch.Size([32, 48, 100])
mu 1
I unfold shape torch.Size([32, 73728])
mu core shape torch.Size([32, 48, 100])
after mu core shape torch.Size([32, 48, 100])
after mu-1 core shape torch.Size([1, 32, 32])


In [5]:
x = torch.rand(batch_size, seq_length, d, requires_grad=True)
pred = model(x)
loss = pred.norm()
loss.backward()

In [38]:
pred.shape

torch.Size([128, 2, 3072])

In [6]:
pred

tensor([[[-6.8387e-01, -6.8614e-01, -6.7008e-01,  ..., -9.1900e-03,
           4.2511e-02, -5.3624e-03],
         [-7.0395e-01, -6.8904e-01, -7.0480e-01,  ...,  1.4223e-02,
           6.0561e-02,  1.2747e-02]],

        [[-6.7816e-01, -6.8328e-01, -6.6265e-01,  ..., -2.7909e-02,
           1.6486e-02, -2.1763e-02],
         [-7.6774e-01, -7.5060e-01, -7.2945e-01,  ..., -3.2468e-02,
           1.2561e-02, -2.6285e-02]],

        [[-7.2998e-01, -7.1110e-01, -6.9610e-01,  ..., -2.2482e-02,
           2.0100e-02, -2.0374e-02],
         [-7.2197e-01, -7.0705e-01, -6.9191e-01,  ...,  1.8200e-04,
           5.0932e-02,  1.2705e-02]],

        ...,

        [[-6.6851e-01, -6.8161e-01, -6.5921e-01,  ...,  2.5525e-03,
           4.0382e-02,  5.3902e-03],
         [-7.0029e-01, -6.9379e-01, -6.6687e-01,  ..., -1.2128e-02,
           3.5532e-02, -1.3287e-02]],

        [[-6.9505e-01, -6.6938e-01, -6.4637e-01,  ..., -5.9292e-02,
          -7.0948e-03, -4.5499e-02],
         [-7.2062e-01, -7.1726e-0

In [39]:
pred

tensor([[[ 1.2202,  1.1765,  1.2157,  ..., -1.0212, -1.0151, -1.0165],
         [ 1.1238,  1.0942,  1.1399,  ..., -1.0766, -1.0632, -1.0521]],

        [[ 1.1544,  1.1027,  1.1628,  ..., -1.0537, -1.0396, -1.0321],
         [ 1.2175,  1.1742,  1.2266,  ..., -1.0808, -1.0740, -1.0661]],

        [[ 1.1988,  1.1545,  1.2122,  ..., -1.1426, -1.1004, -1.1133],
         [ 1.2190,  1.1511,  1.2163,  ..., -1.1160, -1.1013, -1.0980]],

        ...,

        [[ 1.1751,  1.1343,  1.1980,  ..., -1.0538, -1.0303, -1.0154],
         [ 1.1886,  1.1494,  1.1985,  ..., -1.0659, -1.0546, -1.0536]],

        [[ 1.1125,  1.0685,  1.1359,  ..., -1.0585, -1.0441, -1.0412],
         [ 1.1822,  1.1277,  1.1821,  ..., -1.1470, -1.1309, -1.1276]],

        [[ 1.1669,  1.1203,  1.1805,  ..., -1.1929, -1.1737, -1.1416],
         [ 1.1948,  1.1484,  1.2108,  ..., -1.0790, -1.0773, -1.0409]]],
       grad_fn=<AddBackward0>)

In [30]:
pred

tensor([[[-0.0028,  0.2138, -0.2089,  ..., -0.1052, -0.2332, -0.1846],
         [ 0.0286,  0.1832, -0.2136,  ...,  0.0667, -0.1115, -0.2315]],

        [[ 0.0384, -0.0179, -0.2256,  ...,  0.0807, -0.0470, -0.0163],
         [-0.0651,  0.1629, -0.2195,  ..., -0.0766, -0.3056, -0.1066]],

        [[-0.0749,  0.0814, -0.1657,  ..., -0.0632, -0.0919,  0.0690],
         [-0.0457,  0.0322, -0.1306,  ...,  0.1305, -0.1684, -0.1863]],

        ...,

        [[ 0.0349,  0.0993, -0.1675,  ..., -0.0289, -0.1185, -0.0966],
         [ 0.0256,  0.0426, -0.2075,  ...,  0.0911, -0.0559, -0.0202]],

        [[-0.0354,  0.0904, -0.2423,  ..., -0.0048, -0.0123, -0.1131],
         [-0.0896,  0.1158, -0.1183,  ..., -0.0708, -0.1666, -0.0247]],

        [[-0.1663, -0.0460, -0.1139,  ...,  0.0824, -0.0593, -0.1061],
         [ 0.0727,  0.1929, -0.2329,  ..., -0.0156, -0.1999, -0.0772]]],
       grad_fn=<AddBackward0>)

In [19]:
a = TTLinear(in_features = 3072, out_features = 768, ranks =[72, 72, 72] , input_dims = [8, 8, 6, 8], output_dims= [4, 6, 8 ,4])

In [22]:
a

TTLinear(
  (cores): ParameterList(
      (0): Parameter containing: [torch.FloatTensor of size 1x8x4x32]
      (1): Parameter containing: [torch.FloatTensor of size 32x8x6x72]
      (2): Parameter containing: [torch.FloatTensor of size 72x6x8x32]
      (3): Parameter containing: [torch.FloatTensor of size 32x8x4x1]
  )
)

In [20]:
b = torch.rand(1, 100, 768)
weights = torch.rand(768, 3072)
(b@weights).shape

torch.Size([1, 100, 3072])

In [21]:
a(b)

RuntimeError: shape '[1, 100, 768]' is invalid for input of size 19200

In [ ]:
from ttensor_fisher import CustomTensor

tt = CustomTensor(tensor, fisher_tensor, ranks_tt=ranks, batch=self.batch)